# Introduction

Terme forgé en 1948 par Karl Popper pour désigner une tendance à attribuer la cause de phénomènes sociaux ou politiques à *certains individus ou groupes puissants* (Sages de Sion, impérialistes, capitalistes), ce qui dénote selon Popper une incapacité à percevoir dans la réalité une multiplicité de phénomènes agissant de manière interdépendante

Les caractéristiques du discours conspirationniste comporte les caractéristiques suivantes : 

- **un discours sensationnaliste**

- **un discours réducteur sur les causes** (la volonté occulte de quelques individus fait disparaître les contraintes liées aux structures sociales), une cause simple, une catégorie d'individus est responsable de tous les maux.

- **un discours qui se prétend une alternative à une vérité officielle** (déconsidérée en tant qu'officielle). "En même temps la vérité officielle est tellement factice qu'il n'est pas difficile à une personne commune de découvrir la vérité sur Internet en faisant quelques recherches"
