# Les théories du complot sont-elles bien des théories ?

## ambiguité du terme théorie

en anglais theory dans un usage non-scientifique qualifie, souvent de façon négative, une idée postulée sans preuves "come on, it's just a theory"
Conspirationism theory est doublement péjoratif. 

Dans les langues européennes et notamment en français et en italien, la theoria ou théorie est une activité valorisée par l'idéalisme philosophique pregnant dans ces deux cultures.

En anglais conspiracy theorists pourrait se traduire par "mystificateurs", mais en français par "théoriciens du complot", ce qui implique un engagement plus important et une pratique plus raffinée que la simple affabulation. 

(source : [@wuming1CommeQomplotComment2022a], p122)




## théories infalsifiables

Si on considère que les théories doivent être [[falsifiables]], ce n'est pas le cas des théories conspirationnistes. En effet, les preuves qui devraient mettre fin à ces théories ne sont jamais suffisantes pour ceux qui les propagent. 
La présentation du certificat de naissance de Barack Obama qui lui a servi tout au long de sa vie ne parviendra jamais à satisfaire les "birthers", les photos de la terre rond prises par les agences spaciales ne seront jamais pris en compte par les "flatters".
toute preuve allant à l'encontre de la théorie ne fait qu'illustrer la profondeur du complot et le pouvoir de ceux qui le servent et qui ont le moyen de créer des preuves aussi vraisemblables [@andrejevicInfoglutHowToo2013a].

> The fact that there were published announcements of Barack Obama's birth  in Hawaiian newspapers, for example, serves only to illustrate how far back in time the tentacles of conspiracy can reach: either by creating fake articles (can anyone prove  that the copies in the library are authentic?) or by tracing  its roots to a well-thought-out, long-term plan to eventualy place a recently born baby in the White House