# Controverse sur la réalité d'une recrudescence du complotisme à l'âge d'internet

Cette théorie d'une déferlante complotiste suscitée par Internet et en particulier par les réseaux sociaux est sujete à caution. 
Ces détracteurs, par ailleurs souvent pointus dans le domaine de la sociologie des [[croyances]] (Alessio Motta) ou bien sur la question des [[algorithme|algorithmes]] de partage ([[Dominique Cardon]]) font valoir à l'encontre de cette théorie que : 

- On n'a pas de recul sur les temps qui ont précédé Internet ou les attentats du World Trade Center. Des phénomènes très médiatiques, comme la mise en scène de l'autopsie de la créature de Roswell par la télévision ou bien deux décennies plus tôt la rumeur d'Orléans, étudiée par [[Edgar Morin]], montrent que ces rumeurs ont également été largement propagées dans la société française et semblent indiquer une certain permanence du phénomène. Ce qui a changé, c'est la traçabilité de la rumeur qui est devenue beaucoup plus quantifiable grâce aux réseaux sociaux numériques. Ce qui a changé également, c'est qu'on explique aujourd'hui le succès de ces théories complotistes par les failles de cerveaux individuels (les biais cognitifs considérés sans discernement comme des failles) dans une perspective individualiste alors que dans les années 60 (cf. La rumeur d'Orléans) les explications apportées étaient d'ordre sociologique et interrogeait la circulation de la rumeur dans un contexte donné. 
- Le besoin de croire à une déferlante complotiste est issu du besoin de reconnaissance du journaliste. Ce dernier aura du mal à insérer dans son journal une théorie qui relativise le phénomène alors qu'il est beaucoup plus vendeur de s'adresser à des experts de plateaux, à la lisière du champ scientifique comme [[Rudy Reichstadt ]](Conspiracy Watch) ou bien [[Gérald Bronner]] pour dramatiser un phénomène social comme le complotisme. Dénoncer le complotisme en ligne, en tant que journaliste, expert (ou bibliothécaire ?) revient aussi à justifier l'importance de son travail aux yeux de la société.
- Les enquêtes dont on se sert pour manifester l'ampleur du phénomène sont biaisées : 
     * elles mettent sur le même plan des théories simplistes et des théories beaucoup plus controversées
     * elles ne permettent pas au répondant d'indiquer qu'il ou elle ne connaît pas la théorie du complot
     * elles n'essaient pas de mesurer le sérieux avec lequel l'enquête est faite  ([@Mottadeferlantecomplotisteou2021]): 
     > Elles étaient présentées sous la forme d’une assez longue série, telle qu’il était difficile – c’est un biais fréquemment observé dans les recherches sur les sondages d’opinions – de répondre constamment « pas d’accord ». Telle aussi qu’il ne faut pas négliger la part de celles et ceux qui n’ont pas pris le sondage au sérieux et se sont amusés à répondre des absurdités. Ces mêmes sondés étaient aussi obligés de se prononcer sur des théories qu’ils ne connaissaient pas. On ne leur proposait pas « ne se prononce pas »
        
		
	Certaines analyses convergent pour pointer du doigt à travers cette adhésion aux thèses complotistes les classes moyennes inférieures ou populaires (cf. Gilets jaunes) tout en omettant que les classes plus aisées sans y adhérer moins savent davantage évoquer ces théories avec un discours plus convenable, savent s'[[auto-censure|auto-censurer]] quand il le fait, connaissant les effets que suscitent l'énoncé de telle ou telle théorie auprès de tel ou tel public. 
	Alessio Motta remet en cause l'existence même d'une mentalité complotiste homogène : 
	
	>Or, les entretiens approfondis existant sur la question montrent que le terme « complotisme » couvre des réalités extrêmement diverses : [[croyances]] multiples profondément ancrées, curiosité sporadique sur une question d’actualité, implication réelle ou dérision.

Par ailleurs, comme Dominique Cardon (et Sylvain Delouvée[@DelouveeRepeterestpas2015]), Alessio Motta montre qu'une grande partie des mentions faites aux *Illuminati* et aux platisme sont faites sur les réseaux sociaux par des comptes qui se moquent ouvertement de ces théories (voir chapitre suivant). Cette absence de distinction entre les adhésions réelles et les citations sceptiques ou moqueuses entrave la production de chiffres fiables sur l'adhésion aux thèses complotistes.

Quant à la quantification du phénomène sur les réseaux sociaux, les grands chiffres annoncés sont à mettre en perspective avec l'ampleur prise par l'usage d'Internet dans nos vies. 

>Sur Facebook, les vingt infox les plus partagées lors de la campagne électorale qui a élu Donald Trump, l’ont été 8 711 000 fois, alerte [Buzzfeed](https://www.buzzfeednews.com/article/craigsilverman/viral-fake-election-news-outperformed-real-news-on-facebook)**.** [Le chiffre impressionne, mais il correspond à 0.006% des informations partagées sur Facebook aux États-Unis pendant la même période](https://www.cjr.org/analysis/fake-news-media-election-trump.php) !

(Dominique Cardon [@CardonPourquoiavonsnoussi2019])

L'égalitarisme de façade des réseaux sociaux (ce sont surtout les personnes les plus mobilisées sur le plan politique qui y sont actives) et l'effet de masse que l'on ressent quand on y passe du temps survalorise, aux yeux de la presse, la pregnance de certaines opinions et de certains messages de désinformation : 

>Alimentée par les métriques qui de toute part quantifient les centaines de reprises d’un tweet, les milliers de vues d’une vidéo YouTube, combinée avec l’égalitarisme apparent de plateformes où chacun est libre de s’exprimer, cette impression conduit de nombreux journalistes et commentateurs médiatiques à traiter l’espace public numérique comme une vue aérienne du corps social français, quand il n’en est en réalité qu’un zoom particulièrement spécifique. C’est ce qui rend délicate toute prédiction électorale basée sur l’expression en ligne 

pour autant, bcp de rédactions se servent des *trending topics* sur Twitter (désinformation comprise) pour prioriser les informations qu'ils vont servir à leur public

Si en nombre de visites, l'augmentation de l'audience des sites de désinformation a augmenté, c'est le cas aussi des sites web qui diffusent de l'information fiable. Par ailleurs l'étude de Grinberg, Joseph et Friedland montrent que 1% seulement des comptes Twitter ont été exposés pendant la campagne présidentielle américaine de 2016 à 80% des tweets publiés et pouvant être classés comme complotistes[@GrinbergFakenewsTwitter2019].  

## Répéter n'est pas croire


### effet d'exposition à une fausse information

Une expérience a montré que lorsqu'on exposait à deux groupes (groupe A et groupe B) dans un cas une brochure expliquant l'avantage de la vaccination et les risques de la non-vaccination (groupe A) et dans l'autre groupe un exposé des vérités relatives à la vaccination et en regard des mythes qui circulent à son sujet (Groupe B), le groupe A avait tendance à opter plus facilement pour le vaccin que le groupe B. L'exposition à des théories présentées comme fausses peut avoir un effet contraire à celui qui était escompté. [@MAZETAutodefenseintellectuelle2020](p194)

Cela rejoint le concept de [[biais d'exposition]]


### Difficulté à distinguer les types de citation de la théorie complotiste

A ce titre elles attirent même lorsqu'elles n'entraînent pas la conviction. On peut partager une [[théorie complotiste|théorie du complot]], non pas parce qu'on y croit mais parce qu'on la trouve originale, amusante, ou représentative de son époque. 

Les analystes des fausses théories contribuent d'ailleurs à les faire proliférer sur le web en les mentionnant seulement. Cela ne veut pas dire que ces théories gagnent de nouveaux adeptes, juste qu'il en est davantage question. Il n'est pas rare d'apprendre à un public donné l'existence d'une théorie conspirationniste comme les [[chemtrails]] et de renforcer ainsi sa visibilité sur les réseaux sociaux (voir travaux de Sylvain Delouvée à ce sujet) De même qu'on peut adhérer à une théorie conspirationniste sans la transmettre, de même on peut la transmettre sans y adhérer. 

Le web n'est pas pour la plupart des gens d'abord un lieu où on s'informe, mais plutôt un outil avec lequel on se divertit. Le mix, mashup, [[mèmes]] à partir de ces théories fait partie de la créativité qu'on voit à l'oeuvre sur les réseaux. 

Répéter n'est donc pas forcément croire. 

>Rien ne permet de le dire et il est plus que probable que la réalité des réceptions numériques est tout sauf « forte ». Dans un univers aussi saturé d’informations, marqué par le déclin de la confiance envers les médias et une augmentation du [[capital culturel]], les mondes de la réception ne cessent avec le numérique de se complexifier en multipliant les niveaux lectures, les régimes interprétatifs et les formes d’appropriation. **Tout ceci rend le questionnement _il y croit/il n’y croit pas_ particulièrement simpliste, désuet et paternaliste.**

>On peut partager des informations « fausses » sans penser pour autant qu’elles soient vraies, parce qu’on veut les dénoncer, parce que « je sais bien, mais quand même… », parce que la mise en conversation d’informations surprenantes, choquantes ou polémiques autorise toutes formes d’[[usages]] sociaux et apporte des gratifications multiples (faire rire, provoquer, animer le débat, etc.). Plus que jamais**,** [comme y invite depuis longtemps la sociologie des croyances](https://www.editionstextuel.com/livre/le-vertige-des-faits-alternatifs), la question est moins de savoir si les gens pensent que les informations sont « vraies » ou « fausses », que d’explorer les [[usages]] variés, contextuels, à multiples niveaux d’interprétation, qu’ils peuvent en faire, notamment dans cette forme particulière d’échange qu’est la sociabilité numérique [@CardonPourquoiavonsnoussi2019]